// Importing createSlice from Redux Toolkit to help create a slice of the Redux state
import { createSlice } from '@reduxjs/toolkit';

const uiSlice = createSlice({
  name: 'ui', // Name of the slice in the Redux store is 'ui'
  initialState: { cartIsVisible: false }, // Set initial state: cartIsVisible is false (cart hidden)
  reducers: {
    toggle(state) {
      // Reducer function to handle toggling cart visibility
      state.cartIsVisible = !state.cartIsVisible; // Invert the current cartIsVisible state; if true, set to false, and vice versa
    }
  }
});

export const uiActions = uiSlice.actions; // Export action creators automatically generated by createSlice

export default uiSlice; // Export the slice itself as the default export